# Generated by Django 3.1.5 on 2021-01-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=40)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
    ]
