# Generated by Django 3.1.5 on 2021-01-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='company@company.com', max_length=50),
            preserve_default=False,
        ),
    ]
