# Generated by Django 3.1.5 on 2021-01-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_employeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeer',
            name='username',
            field=models.CharField(default='liupTi', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
