# Generated by Django 3.1.5 on 2021-01-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_employeer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
