# Generated by Django 3.1.5 on 2021-01-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_company_inscricao_municipal_estadual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='inscricao_municipal_estadual',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employeer',
            name='cpf',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
